on-unmatched = "info"

[formatter.alejandra]
command = "alejandra"
includes = ["**/*.nix", "*.nix"]

[formatter.stylua]
command = "stylua"
includes = ["**/*.lua", "*.lua"]
indent_type = "Spaces"
indent_width = 2
column_width = 120

